export const TYPES_BTS = {
    GET_BTS_CARTUCHERAS: "GET_BTS_CARTUCHERAS",
    GET_BTS_POLOS: "GET_BTS_POLOS",
    GET_BTS_LIBRETAS: "GET_BTS_LIBRETAS",
    GET_BTS_COJINES: "GET_BTS_COJINES",
    GET_BTS_TAZAS: "GET_BTS_TAZAS",
    GET_BTS_COJINES_MID: "GET_BTS_COJINES_MID",
    GET_BTS_POSTER: "GET_BTS_POSTER",
    GET_BTS_MEDIAS: "GET_BTS_MEDIAS",
    ALL_GET_CATEGORIES_BTS: "ALL_GET_CATEGORIES_BTS",
    CURRENTLY_CATEGORY_BTS: "CURRENTLY_CATEGORY_BTS",
    GET_BTS_CATEGORIES:"GET_BTS_CATEGORIES",
    GET_BTS_COMBOS:"GET_BTS_COMBOS",
    GET_BTS_COMBOS_FILTER:"GET_BTS_COMBOS_FILTER"
 }