 export const TYPES = {
    GET_POLOS_SUBLIMADOS:'GET_POLOS_SUBLIMADOS',
    GET_TAZAS_SUBLIMADOS:'GET_TAZAS_SUBLIMADOS',
    GET_COJIN_SUBLIMADOS:'GET_COJIN_SUBLIMADOS',
    GET_SUBLIMADOS:'GET_SUBLIMADOS',
    GET_BTS_CATEGORIES:'GET_BTS_CATEGORIES',
 }