export const TYPES_SUBLIMADOS = {
    GET_TAZAS_SUBLIMADOS_PLANTILLAS: "GET_TAZAS_SUBLIMADOS_PLANTILLAS",
    GET_CATEGORIES_TAZAS_SUBLIMADOS_DISENOS: "GET_CATEGORIES_TAZAS_SUBLIMADOS_DISENOS",
    GET_TAZAS_SUBLIMADOS_SAN_VALENTIN_LIQUIDACION:"GET_TAZAS_SUBLIMADOS_SAN_VALENTIN_LIQUIDACION"
 }